### PR TITLE
Austin lynes

### PR DESCRIPTION
**Pull request by AustinLynes**
Completed Sprint Challenge

### CODE REVIEW

**Review by secantsquared — CHANGES_REQUESTED** [review]
Excellent work, and so close to MVP, just need to fix a few things to get there.  
1.  Link back to the index page from the About page.
2. Fix the header on the main page it seems to be outside the main container or not aligned in the same container that everything else is (notice when you move the viewport or browser size from left to right/right to left)
3.  Fix the borders on the about page... they should be the same style as the index page and the design files.  Also the middle set of borders are missing and those including the ones on the bottom should be split in the middle and not one continuous border going across the entire width of the section.  The top border is one solid border and that is fine once the style is matched.


Let me know if you have any questions, I am also going to send you a DM with more instructions and information on the logistics of the fixes, however, honestly these are minor fixes that you can probably do very quickly, and I will touch base with you and we will establish that plan.  Really, the hard stuff is done and it is done well, so these changes will be straight forward.

**Comment by AustinLynes** [comment]
So I failed and have to redo now?

**Comment by ryanboris** [comment]
Check your slack message.

**Comment by secantsquared** [comment]
@AustinLynes No, check your Slack messages.

**Review by secantsquared — APPROVED** [review]

**Comment by secantsquared** [comment]
Great job making those small fixes, and reaching MVP - overall great work and persisting through in order to hotfix the small issues - that is a great quality to have in the industry.
@AustinLynes

**Pull request merged**
